### ISSUE TITLE
SugarCalendar - Link not being added to the ics

### ISSUE THREAD

**Issue by ajolo2ky** [OpenSourceOrg/dotOrg#34]
### Description

Setting up an event with a meeting link works but when adding that event to Google or other calendars, the meeting link isn't present there

### Steps to reproduce

Sign up for https://opensource.org/events/open-source-ai-definition-town-hall-3
Then click Add to calendar button
See the calendar details, the meeting link won't be there (unless added as location, which is the current work around)

### What you expected to happen

The meeting link getting populated in the calendar invite

### What actually happened

No link gets added to the invite (the one you'll see for location was manually added as a workaround)

**Comment by nickpagz** [comment]
Hi @ajolo2ky 

Since the ICS format doesn't support meeting links, we're thinking the best current option is to automate the workaround and add the link to the location field if it's empty. It's almost ready to go in this [PR](https://github.com/Vrishabhsk/dotOrg/pull/2). 

An alternative is not do anything at all, since technically, this isn't really a bug and just a limitation of the ics format. 

Let me know what you think.

**Comment by smaffulli** [comment]
I'd go with the location as I think most calendar applications are using that field anyway.

**Comment by webmink** [comment]
Putting a URL in the Location field of a Google Calendar appointment is not a good idea. Google tries to treat it as an address and attempts to draw a map. The URL is not clickable by recipients and causes frustration. If there is no Location, the URL should be placed in the Description instead.

**Comment by nickpagz** [comment]
Going back to the original issue description, I've confirmed the meeting link is **_only_** missing on the Google Calendar invite. For the other calendar types, the meeting link is appended to the description, so it already exists. Including it in the location field is a nice to have, but not strictly necessary.

Now, adding it to the location field generally works for all calendars, except when adding it to Google Calendar on a mobile device (tested only on iPhone so far). The meeting link will be stripped from the location field in this case. As such, it would be ideal to **_also_** have the meeting link included in the description for Google Calendars. Unfortunately, the Sugar Calendar plugin doesn't do this for the Google Calendar option (handled by a different function than the other calendar types). It's not clear if this is intentional, or a bug. There's also no easy way to hook into this function, and it would have to be modified directly to get it added.

**Comment by ajolo2ky** [comment]
If that’s the case could you submit this code back to mainstream and work
with the team? We don’t want to maintain a separate version

**Comment by ajolo2ky** [comment]
Closing as we are no longer using SugarCalendar
