### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by ajolo2ky** [OpenSourceOrg/dotOrg#39]
### Description

For some reason this event's page is completely broken: https://opensource.org/?post_type=sc_event&p=16099&preview=true

It is now a draft because I had to unpublish it, copy one of the others we had produced and publish it under the same permalink we were originally using for this one.

### Steps to reproduce

Go to https://opensource.org/?post_type=sc_event&p=16099&preview=true

### What you expected to happen

The page should be displayed accordingly

### What actually happened

<img width="1792" alt="image" src="https://github.com/OpenSourceOrg/dotOrg/assets/6595356/876fe459-8ba3-4d98-87f6-052f968e31ee">

**Comment by nickpagz** [comment]
@ajolo2ky 

>I'll try to find out a bit more on why this is happening with this template

These are coming from a custom template you created in the Site Editor (FSE). This must of have been a while back, and I'm assuming the site editor was available at some point. However, being a classic theme, the templates aren't editable, and only exist in the database, ie not as part of the theme files. They still however, get picked up in the page/post editor.

Since these aren't used, I can just delete them from the database. Let me know if that's ok.

**Comment by smaffulli** [comment]
Feel free to delete the template that aren't being used, thanks

**Comment by nickpagz** [comment]
Thanks @smaffulli 

I've gone ahead and removed those from the database.

As it turns out, it looks like it's possible to create templates while editing a post, something that shouldn't happen on a classic theme. It could be the existence of the theme.json causing it, but something I'll test further and see if we can disable that option.

**Comment by nickpagz** [comment]
I don't see any options to disable it, it seems to be a "feature" of hybrid themes, which this one is. I'll go ahead and close this issue, but feel free to re-open is needed.

**Comment by nickpagz** [comment]
Closed.
