### ISSUE TITLE
SugarCalendar: Recurrence shows the wrong information on the front end

### ISSUE THREAD

**Issue by smaffulli** [OpenSourceOrg/dotOrg#55]
### Description

When setting up the recurrence to every other week one would expect the information on the front end to be shown correctly.

I set this event to recur every two weeks:

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1348736/4ff9db50-a01a-489d-b7bb-1a0487527cc8)

but the frontend shows the event repeating weekly, which is wrong.

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1348736/e89b0fa1-7a1a-4a78-8462-7366f4a87fe7)

**Comment by nickpagz** [comment]
It looks like the Advanced Recurring extension doesn't provide any output formatting options for the more complex recurring patterns, such as repeating events with "every" 2 or 3 weeks/months etc intervals.

I've reached out to Sugar Calendar support to ask for some help or direction, albeit without the license key used to purchase the extension, so I'm not sure they'll help.

In the meantime I've come up with my own version of the formatting function that tries to give us a useable format for some of the cases. This can be seen in PR #63 
Please note the exceptions/cases not currently covered in the PR description.

**Comment by nickpagz** [comment]
@smaffulli So based on the response from Sugar Calendar it doesn't look like they've got an ETA for a fix on this. I've also reviewed their work-around, and I think this won't work either as modifying the translation string could/would affect all other events on the site. 

I can continue working on the PR I started (mentioned in the previous comment), but since this will use a custom function for generating the text, if/when a fix comes out from Sugar Calendar the site won't use it until we revert the changes made in the PR.

I think it boils down to how urgent this is. Do you have existing events where you need this functionality? Or can it wait? I'm completely open to whatever option you choose, and happy to work on progressing the PR if needed.

Thanks!

**Comment by smaffulli** [comment]
This can wait. We've asked concierge also to suggest alternative tools
because Sugar also has issues with registrations to events, it doesn't
support free events.

**Comment by ajolo2ky** [comment]
Closing as we are no longer using SugarCalendar
