### ISSUE TITLE
OpenSource.org | Add a Discourse comments to post template

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#72]
Even though the comments display in the Discourse plugin is on, the actual comments are not displaying. We need to update the post templates to display the bits the Discourse plugin is trying to show.

## Details

- [This post](https://opensource.org/blog/cra-standards-request-draft-published) has an automatically created Discourse topic [here](https://discuss.opensource.org/t/cra-standards-request-draft-published/323)
- Based on the [Discourse Commenting Settings](https://opensource.org/wp-admin/admin.php?page=commenting_options), the link to that topic should be showing on the bottom of that post (there's a manually added link now)

I suppose we're missing the "comments" part of the post template?

Useful links:
- [Install and configure the WP Discourse WordPress plugin for Discourse](https://meta.discourse.org/t/install-and-configure-the-wp-discourse-wordpress-plugin-for-discourse/50752)
- [Customize the structure of WP Discourse templates](https://meta.discourse.org/t/customize-the-structure-of-wp-discourse-templates/50754)

**Comment by bernattorras** [comment]
By default, the link to the Discourse post appears if you enable the comments in the post settings:

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1201868/dac4ebe4-3e39-45e2-b08d-ec745f35986f)

Once enabled, you can see the link here:

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1201868/a92ac567-c6e4-4cfb-8542-d433209ef355)

@toncijajic can you check with the partner the following things?
- Do they want to show the link this way or do we need to style it?
- If they want to change the option to show comments instead of that link, I'd suggest to add (or wait for) some comments in Discourse and see how are they rendered in the post page, as they will probably need some styling as well. 

Thanks

**Comment by nickvidal** [comment]
Thanks @bernattorras, I didn't realize you had to enable Comments. I think that solves it.
